project:
  type: website
  output-dir: docs
  render:
    - website/*.qmd

website:
  title: "The Avian MetaNetwork"
  site-url: https://avianmetanetwork.github.io
  navbar:
    left:
      - href: website/index.qmd
        text: Home
      - href: website/about.qmd
        text: About
      - href: website/team.qmd
        text: Meet the team
      - href: website/using-data.qmd
        text: Using the data

format:
  html:
    theme:
      - darkly
      - styles/darkly-green.scss
    toc: false
    smooth-scroll: true
